services:
  python:
    build:
      context: ./mqttclient
      dockerfile: ./Dockerfile
    container_name: endpoint-mqttclient
    restart: unless-stopped
    volumes:
      - ./mqttclient/:/app
    ports:
      - "1883:1883"

  db:
    image: postgres:alpine
    container_name: endpoint-postgres
    volumes:
      - ./postgresql/postgresdata:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: varilamysickakasicku
      POSTGRES_DB: temperature_data
    ports:
      - "5432:5432"

